// DEAL IMPORT planner — PURE. Consumes Snapshot #1 facts + the decision ledger +
// the frozen stage_config + the identity crosswalk, and produces the canonical
// Deal import payloads, deterministically.
//
// ── THE CONTRACT ──────────────────────────────────────────────────────────────
//  * Undecided deals import UNCHANGED (the honest default). Deal decisions
//    (queue 'deals') override: import / import_corrected / merge / exclude /
//    deleted. No split.
//  * stage_config is BINDING: pipeline+stage names → GOS stage keys, approved at
//    the 2026-07-14 spec freeze. Only unmapped-with-deals is an anomaly. Source
//    status is preserved independently of stage; historical WON/LOST are plain
//    column values — the importer never walks live transition paths.
//  * Identity resolves EXCLUSIVELY through the crosswalk. Never by name, phone,
//    email or organization text. A dangling reference is a REPORTED problem,
//    never a silent placeholder.
//  * Uncertain mappings are NOT invented: unmappable values land as readable
//    label→value rows in LegacyRecord.cardData; URLs (Drive/Photos) import as
//    links only (rule:drive_photos_links_only).
//  * DETERMINISTIC: stable ordering + canonical serialization; the rehearsal
//    hash must be identical across runs, and the production run must produce
//    the same payload hash the owner approved.
//
// ── WRITE-BOUNDARY (audited 2026-07-16) ───────────────────────────────────────
// Live side effects (tour creation, WON automation, calendar sync, WhatsApp,
// email, tasks, quotes, payments, accounting, notifications) all live in the
// ROUTE/SERVICE layer (routes/deals.js transitions and their hooks) or are
// driven by Bookings (control detectors iterate active bookings; there is no
// prisma middleware and no DB trigger on Deal). The importer writes
// prisma.deal.createMany + dealContact.createMany + legacyRecord.createMany
// DIRECTLY, creates no Booking, and therefore triggers none of them. Validation
// is preserved by mapping onto the same columns the API validates.
import crypto from 'node:crypto';

const t = (s) => String(s ?? '').trim();
const sha256 = (s) => crypto.createHash('sha256').update(s).digest('hex');

// Custom-field hashes are NEVER hardcoded here — they resolve from the snapshot's
// own reference bundle BY NAME (resolveFieldKeys below), so the planner can only
// map a field it can prove. Only RELIABLE mappings become Deal columns.
//
// Map option labels → GOS string enums. Anything else stays on the legacy card.
const ACTIVITY_TYPE = { 'פרטי': 'private', 'קבוצתי': 'group', 'עסקי': 'business' };
const COMM_LANG = { 'עברית': 'he', 'אנגלית': 'en' }; // GOS supports he|en only
const TOUR_LANG = { 'עברית': 'he', 'אנגלית': 'en', 'רוסית': 'ru', 'צרפתית': 'fr', 'ספרדית': 'es' };

// Reference-bundle field resolution by NAME (stable; hashes could in principle be
// regenerated by Pipedrive, names are the owner's own labels).
export function resolveFieldKeys(dealFields) {
  const byName = new Map((dealFields || []).map((f) => [t(f.name), f]));
  const key = (name) => byName.get(name)?.key || null;
  const options = (name) => new Map((byName.get(name)?.options || []).map((o) => [String(o.id), o.label]));
  return {
    tourDate: key('תאריך הסיור'),
    tourTime: key('שעת הסיור'),
    participants: key('כמות משתתפים'),
    activityType: key('סוג פעילות'), activityTypeOpts: options('סוג פעילות'),
    commLang: key('שפת התקשורת מול הלקוח'), commLangOpts: options('שפת התקשורת מול הלקוח'),
    tourLang: key('שפת ההדרכה'), tourLangOpts: options('שפת ההדרכה'),
    customerInfo: key('מידע חשוב על הלקוח'),
    paymentTerms: key('תנאי תשלום - לקוחות עסקיים'), paymentTermsOpts: options('תנאי תשלום - לקוחות עסקיים'),
    paymentMethod: key('אמצעי תשלום בפועל'), paymentMethodOpts: options('אמצעי תשלום בפועל'),
    location: key('מיקום הסיור'), locationOpts: options('מיקום הסיור'),
    graffitiFood: key('פעילות גרפיטי/אוכל'), graffitiFoodOpts: options('פעילות גרפיטי/אוכל'),
    invoiceNotes: key('הערות נוספות לחשבונית - עסקיים'),
    // Everything ELSE that carries a value lands on the legacy card generically.
    labelOf: (k) => byName.size ? [...byName.values()].find((f) => f.key === k)?.name || null : null,
    optionLabel: (k, v) => {
      const f = [...byName.values()].find((x) => x.key === k);
      const opt = (f?.options || []).find((o) => String(o.id) === String(v));
      return opt ? opt.label : null;
    },
  };
}

// ── stage mapping: frozen config rows → stage_id lookup ───────────────────────
// stage_config keys by NAME; the snapshot reference gives id→name. Two stages
// were renamed in Pipedrive after the freeze — the aliases are explicit, never
// fuzzy. A pipeline mapped as 'כל השלבים' covers every stage in it.
const PIPELINE_ALIAS = {
  'מכירות גרפיטיול': 'מכירות',
  'לקוחות עסקיים': 'לקוחות עסקיים',
  'לקוחות עסקיים - גבייה': 'לקוחות עסקיים - גבייה',
  'לקוחות לפלואפ רחוק': 'פולואפ רחוק',
  'שוברי מתנה': 'שוברי מתנה',
};
const STAGE_ALIAS = {
  'בהמתנה- לא לשלוח פולואפים': 'בהמתנה',
  'לא לשלוח פולואפים - בהמתנה': 'לא לשלוח פולואפים',
};

export function buildStageMap({ stageConfigRows, pipelines, stages }) {
  const configTarget = new Map(); // 'pipelineAlias:stageName' → gos stage key
  const wholePipeline = new Map(); // pipelineAlias → gos stage key
  for (const r of stageConfigRows) {
    const p = r.proposal;
    if (p?.kind !== 'stage_mapping') continue;
    if (p.stage === 'כל השלבים') wholePipeline.set(p.pipeline, p.targetStage);
    else configTarget.set(`${p.pipeline}:${p.stage}`, p.targetStage);
  }
  const pipelineName = new Map((pipelines || []).map((x) => [x.id, t(x.name)]));
  const byStageId = new Map();
  const unmapped = [];
  for (const s of stages || []) {
    const alias = PIPELINE_ALIAS[pipelineName.get(s.pipeline_id)] || pipelineName.get(s.pipeline_id);
    const stageName = STAGE_ALIAS[t(s.name)] || t(s.name);
    const target = configTarget.get(`${alias}:${stageName}`) ?? wholePipeline.get(alias) ?? null;
    if (target) byStageId.set(s.id, { target, pipeline: alias, stage: t(s.name) });
    else unmapped.push({ stageId: s.id, pipeline: alias, stage: t(s.name) });
  }
  return { byStageId, unmapped };
}

// ── the planner ───────────────────────────────────────────────────────────────
const pid = (v) => (v && typeof v === 'object' ? v.value : v) ?? null;
const URLISH = /^https?:\/\/\S+$/i;
const toMinor = (v) => Math.round(Number(v || 0) * 100);
const iso = (v) => (v ? new Date(v).toISOString() : null);

export function planDealImport({
  deals, participantsByDeal = new Map(),
  dealDecisions = [], stageMap, fieldKeys,
  personXwalk = new Map(),        // sourceId(string) → { entityType, entityId } | null(no entity)
  orgXwalk = new Map(),           // sourceId(string) → entityId
  gosStageIdByKey = new Map(),    // DealStage.key → id (live GOS config)
  users = [],                     // reference users (owner names → legacy card)
  existingDealXwalk = new Map(),  // idempotency: sourceId → entityId
}) {
  const userName = new Map(users.map((u) => [u.id, t(u.name)]));
  const decisionByDeal = new Map();
  for (const r of dealDecisions) {
    const m = /^deal:(\d+)$/.exec(r.subjectKey || '');
    if (m && ['approved', 'edited'].includes(r.status) && r.decision) decisionByDeal.set(Number(m[1]), r.decision);
  }

  const problems = [];
  const warnings = [];
  const payloads = [];
  const stats = {
    sourceDeals: deals.length,
    create: 0, corrected: 0, merged: 0, excluded: 0, ownerDeleted: 0, alreadyImported: 0,
    byStatus: { open: 0, won: 0, lost: 0, other: 0 },
    archived: 0,
    contactsResolvedPrimary: 0, contactsMergedResolution: 0, identityExcludedOrDeleted: 0,
    participantLinks: 0, orgsResolved: 0, unitsResolved: 0,
    noContact: 0, noOrganization: 0, danglingPersonRefs: 0, danglingOrgRefs: 0,
    stageMapped: 0, stageUnmappedWithDeals: 0, statusStageContradictions: 0,
    legacyCards: 0,
  };

  // Deterministic order: by source deal id.
  const ordered = [...deals].sort((a, b) => a.id - b.id);

  for (const d of ordered) {
    const decision = decisionByDeal.get(d.id) || null;
    const status = ['open', 'won', 'lost'].includes(d.status) ? d.status : 'other';
    stats.byStatus[status] += 1;
    if (d.archived) stats.archived += 1;

    if (existingDealXwalk.has(String(d.id))) { stats.alreadyImported += 1; continue; }
    if (decision?.treatment === 'deleted') { stats.ownerDeleted += 1; continue; }
    if (decision?.treatment === 'exclude') { stats.excluded += 1; continue; }
    if (decision?.treatment === 'merge') {
      stats.merged += 1;
      payloads.push({ kind: 'merge', orderNo: d.id, mergeIntoDealSourceId: decision.mergeIntoDealId ?? null });
      continue;
    }
    const corrections = decision?.treatment === 'import_corrected' ? decision.corrections || {} : {};

    // Stage: binding config; a contradiction (won/lost deal in a non-terminal
    // pipeline) is a WARNING (status wins — status is preserved independently).
    const mapped = stageMap.byStageId.get(d.stage_id) || null;
    const stageKey = corrections.stage || mapped?.target || null;
    if (!stageKey) {
      stats.stageUnmappedWithDeals += 1;
      problems.push({ dealId: d.id, kind: 'stage_unmapped', detail: `שלב ${d.stage_id} ללא מיפוי מאושר` });
      continue; // cannot import without a stage — GOS requires it
    }
    const stageId = gosStageIdByKey.get(stageKey) || null;
    if (!stageId) {
      problems.push({ dealId: d.id, kind: 'gos_stage_missing', detail: `שלב היעד ${stageKey} לא קיים בהגדרות GOS` });
      continue;
    }
    stats.stageMapped += 1;

    // Identity — crosswalk ONLY.
    const personId = corrections.contactSourceId ?? pid(d.person_id);
    let primaryContactId = null;
    if (personId != null) {
      const hit = personXwalk.get(String(personId));
      if (hit === undefined) {
        stats.danglingPersonRefs += 1;
        warnings.push({ dealId: d.id, kind: 'person_dangling', detail: `איש קשר מקור ${personId} ללא רשומת crosswalk` });
      } else if (hit?.entityType === 'Contact') {
        primaryContactId = hit.entityId;
        stats.contactsResolvedPrimary += 1;
        if (hit.merged) stats.contactsMergedResolution += 1;
      } else if (hit?.entityType === 'Organization') {
        // The "person" was really an organization — the deal keeps it as its org
        // when it has none of its own.
        stats.identityExcludedOrDeleted += 1;
      } else {
        stats.identityExcludedOrDeleted += 1; // excluded/deleted identity — no contact, by decision
      }
    }
    if (!primaryContactId) stats.noContact += 1;

    const orgSource = corrections.organizationSourceId ?? pid(d.org_id);
    let organizationId = null;
    if (orgSource != null) {
      organizationId = orgXwalk.get(String(orgSource)) || null;
      if (!organizationId) {
        stats.danglingOrgRefs += 1;
        warnings.push({ dealId: d.id, kind: 'org_dangling', detail: `ארגון מקור ${orgSource} ללא ישות (הוחרג או לא יובא)` });
      } else stats.orgsResolved += 1;
    }
    // A person-as-organization fills an org gap.
    if (!organizationId && personId != null) {
      const hit = personXwalk.get(String(personId));
      if (hit?.entityType === 'Organization') { organizationId = hit.entityId; stats.orgsResolved += 1; }
    }
    if (!organizationId) stats.noOrganization += 1;

    // Participants — crosswalk only; excluded/deleted identities silently absent
    // from GOS but COUNTED (never a placeholder).
    const partIds = [];
    for (const pp of participantsByDeal.get(d.id) || []) {
      const hit = personXwalk.get(String(pp));
      if (hit?.entityType === 'Contact' && hit.entityId !== primaryContactId) partIds.push(hit.entityId);
    }
    stats.participantLinks += partIds.length;

    // Status/stage contradiction: terminal status in a non-closing stage is fine
    // historically; OPEN status mapped to 'closing' from the collection pipeline
    // is the real anomaly class (already routed to exceptional) — report only.
    if (status === 'open' && stageKey === 'closing' && mapped?.pipeline === 'לקוחות עסקיים - גבייה') {
      stats.statusStageContradictions += 1;
      warnings.push({ dealId: d.id, kind: 'status_stage', detail: 'עסקה פתוחה בצינור הגבייה — חריג ידוע' });
    }

    // Reliable field mappings; everything else → legacy card.
    const fk = fieldKeys;
    const opt = (key, opts) => (d[key] != null ? opts?.get?.(String(d[key])) ?? String(d[key]) : null);
    const card = [];
    const pushCard = (label, value) => { if (value != null && t(String(value)) !== '') card.push({ label, value: t(String(value)) }); };

    const activityLabel = opt(fk.activityType, fk.activityTypeOpts);
    const commLabel = opt(fk.commLang, fk.commLangOpts);
    const tourLangLabel = opt(fk.tourLang, fk.tourLangOpts);
    const payload = {
      kind: 'create',
      orderNo: d.id, // rule:deal_order_numbers — the Pipedrive id IS the order number
      title: t(corrections.title ?? d.title) || `עסקה ${d.id}`,
      status,
      dealStageKey: stageKey,
      dealStageId: stageId,
      valueMinor: corrections.valueMinor ?? toMinor(d.value),
      currency: t(corrections.currency ?? d.currency) || 'ILS',
      wonAt: status === 'won' ? iso(d.won_time) : null,
      lostAt: status === 'lost' ? iso(d.lost_time) : null,
      lostReason: status === 'lost' ? t(d.lost_reason) || null : null, // legacy display field, honest
      expectedCloseDate: iso(d.expected_close_date),
      activityType: ACTIVITY_TYPE[activityLabel] || null,
      tourDate: d[fk.tourDate] ? String(d[fk.tourDate]).slice(0, 10) : null,
      tourTime: d[fk.tourTime] ? String(d[fk.tourTime]).slice(0, 5) : null,
      participants: d[fk.participants] != null ? Math.round(Number(d[fk.participants])) : null,
      communicationLanguage: COMM_LANG[commLabel] || null,
      tourLanguage: TOUR_LANG[tourLangLabel] || null,
      customerInfo: t(d[fk.customerInfo]) || null,
      source: null, // Pipedrive has no reliable lead-source field — card only
      primaryContactId,
      participantContactIds: partIds.sort(),
      organizationId,
      organizationUnitId: null, // units resolve via org decisions only when a unit member — deferred detail on card
      corrected: decision?.treatment === 'import_corrected',
    };
    if (payload.corrected) stats.corrected += 1;

    // Legacy card: the readable "מידע ממערכת קודמת".
    pushCard('בעלים במערכת הקודמת', userName.get(pid(d.user_id) ?? d.user_id) || null);
    pushCard('צינור ושלב מקוריים', mapped ? `${mapped.pipeline} · ${mapped.stage}` : null);
    if (commLabel && !payload.communicationLanguage) pushCard('שפת התקשורת (מקור)', commLabel);
    pushCard('פעילות גרפיטי/אוכל', opt(fk.graffitiFood, fk.graffitiFoodOpts));
    pushCard('מיקום הסיור (מקור)', opt(fk.location, fk.locationOpts));
    pushCard('תנאי תשלום (מקור)', opt(fk.paymentTerms, fk.paymentTermsOpts));
    pushCard('אמצעי תשלום בפועל (מקור)', opt(fk.paymentMethod, fk.paymentMethodOpts));
    pushCard('הערות לחשבונית (מקור)', d[fk.invoiceNotes]);
    if (activityLabel && !payload.activityType) pushCard('סוג פעילות (מקור)', activityLabel);
    // Drive / Photos / any URL-valued custom field — links only, never bodies.
    for (const [k, v] of Object.entries(d)) {
      if (!/^[0-9a-f]{40}$/.test(k) || typeof v !== 'string' || !URLISH.test(t(v))) continue;
      pushCard(fieldKeys.labelOf(k) || 'קישור ממערכת קודמת', t(v));
    }
    if (card.length) stats.legacyCards += 1;
    payload.cardData = card;

    payloads.push(payload);
    stats.create += 1;
  }

  // Deterministic canonical hash: payloads are already source-ordered; stringify
  // with sorted keys so object-key insertion order can never leak in.
  const canonical = JSON.stringify(payloads, (key, value) => {
    if (value && typeof value === 'object' && !Array.isArray(value)) {
      return Object.fromEntries(Object.entries(value).sort(([a], [b]) => a.localeCompare(b)));
    }
    return value;
  });
  return { payloads, stats, problems, warnings, payloadHash: sha256(canonical), payloadBytes: canonical.length };
}

// ── HARD EXECUTION GATES (owner, 2026-07-16) — refuse before ANY Deal write ───
// `fullPlan` is computed with an EMPTY deal crosswalk: its hash pins the exact
// source + decisions state the owner approved. `execPlan` uses the real
// crosswalk: on a resume it legitimately plans fewer creates, but must always
// account for exactly the approved total.
export function checkDealExecutionGates({ fullPlan, execPlan, expectHash, gosStageIdByKey, foreignOrderNos = [] }) {
  const failures = [];
  if (!expectHash) failures.push('expect-hash חסר — הרצה ללא נעילת hash אסורה');
  else if (fullPlan.payloadHash !== expectHash) {
    failures.push(`ה-hash של התוכנית (${fullPlan.payloadHash.slice(0, 16)}…) שונה מה-hash המאושר (${String(expectHash).slice(0, 16)}…) — הקלט השתנה`);
  }
  if (fullPlan.stats.sourceDeals !== 24359) failures.push(`סך עסקאות מקור ${fullPlan.stats.sourceDeals} ≠ 24,359`);
  if (fullPlan.stats.create !== 24358) failures.push(`תוכנית יצירה מלאה ${fullPlan.stats.create} ≠ 24,358`);
  if (fullPlan.stats.ownerDeleted !== 1) failures.push(`מחיקות בעלים ${fullPlan.stats.ownerDeleted} ≠ 1`);
  if (fullPlan.problems.length > 0) failures.push(`${fullPlan.problems.length} בעיות חוסמות בתוכנית`);
  if (execPlan.stats.create + execPlan.stats.alreadyImported !== 24358) {
    failures.push(`יצירה (${execPlan.stats.create}) + כבר-יובאו (${execPlan.stats.alreadyImported}) ≠ 24,358`);
  }
  for (const key of ['lead', 'contacted', 'quote', 'negotiation', 'stage_a88c9186', 'closing']) {
    if (!gosStageIdByKey.has(key)) failures.push(`שלב היעד ${key} לא קיים בהגדרות GOS`);
  }
  // An orderNo in the legacy range that belongs to a GOS deal we did NOT import
  // means an unrelated deal squatting on a legacy number — refuse.
  if (foreignOrderNos.length) failures.push(`מספרי הזמנה תפוסים ע"י עסקאות זרות: ${foreignOrderNos.slice(0, 5).join(', ')}${foreignOrderNos.length > 5 ? '…' : ''}`);
  return { ok: failures.length === 0, failures };
}

// ── EXECUTOR — the proven identity pattern: chunked createMany, transactional
// chunk boundaries, crosswalk-first idempotency, resume-safe checkpoints.
// FORWARD-CORRECTION strategy: there is no destructive rollback; a bad row is
// corrected by a follow-up decision + re-import of the correction, never by
// deleting history. Writes deal + dealContact + legacyRecord ONLY — no Booking,
// no TourEvent, no TicketRegistration, nothing that can wake live automation.
export async function executeDealPlan(prisma, execPlan, { batchId, snapshotId, chunk = 500, log = () => {}, checkpoint = async () => {} } = {}) {
  const creates = execPlan.payloads.filter((p) => p.kind === 'create');
  const merges = execPlan.payloads.filter((p) => p.kind === 'merge');
  const orderNoToId = new Map();
  let written = 0;

  for (let i = 0; i < creates.length; i += chunk) {
    const slice = creates.slice(i, i + chunk);
    const dealRows = [];
    const contactRows = [];
    const legacyRows = [];
    for (const p of slice) {
      const id = crypto.randomUUID();
      orderNoToId.set(p.orderNo, id);
      dealRows.push({
        id, orderNo: p.orderNo, title: p.title, status: p.status,
        dealStageId: p.dealStageId,
        valueMinor: BigInt(p.valueMinor), currency: p.currency,
        wonAt: p.wonAt ? new Date(p.wonAt) : null,
        lostAt: p.lostAt ? new Date(p.lostAt) : null,
        lostReason: p.lostReason,
        expectedCloseDate: p.expectedCloseDate ? new Date(p.expectedCloseDate) : null,
        activityType: p.activityType,
        tourDate: p.tourDate, tourTime: p.tourTime, participants: p.participants,
        communicationLanguage: p.communicationLanguage, tourLanguage: p.tourLanguage,
        customerInfo: p.customerInfo,
        organizationId: p.organizationId, organizationUnitId: p.organizationUnitId,
      });
      const linked = new Set();
      if (p.primaryContactId) {
        linked.add(p.primaryContactId);
        contactRows.push({ dealId: id, contactId: p.primaryContactId, isPrimary: true });
      }
      for (const cid of p.participantContactIds || []) {
        if (linked.has(cid)) continue; // merge survivors can collapse two sources onto one contact
        linked.add(cid);
        contactRows.push({ dealId: id, contactId: cid, isPrimary: false });
      }
      legacyRows.push({
        sourceSystem: 'pipedrive', sourceType: 'deal', sourceId: String(p.orderNo),
        entityType: 'Deal', entityId: id,
        importBatchId: batchId, snapshotId,
        cardData: p.cardData?.length ? p.cardData : null,
      });
    }
    // One transaction per chunk: a kill mid-chunk leaves NO partial deal (a deal
    // without its crosswalk row would break resume accounting).
    await prisma.$transaction([
      prisma.deal.createMany({ data: dealRows }),
      prisma.dealContact.createMany({ data: contactRows, skipDuplicates: true }),
      prisma.legacyRecord.createMany({ data: legacyRows, skipDuplicates: true }),
    ]);
    written += slice.length;
    await checkpoint({ written, total: creates.length });
    if (written % 2500 < chunk) log(`  ✓ ${written}/${creates.length} deals`);
  }

  // Merge decisions (none in the approved plan, supported for completeness):
  // the merged source crosswalks to its TARGET deal entity.
  for (const m of merges) {
    const targetId = orderNoToId.get(m.mergeIntoDealSourceId) || null;
    if (!targetId) { log(`  ⚠ merge ${m.orderNo}: target ${m.mergeIntoDealSourceId} not in this run — crosswalk row skipped`); continue; }
    await prisma.legacyRecord.createMany({
      data: [{ sourceSystem: 'pipedrive', sourceType: 'deal', sourceId: String(m.orderNo), entityType: 'Deal', entityId: targetId, importBatchId: batchId, snapshotId }],
      skipDuplicates: true,
    });
  }
  return { written, merges: merges.length };
}
