// Travel-agent reservation form — bilingual UI strings (he RTL / en LTR).
// House pattern: per-surface L tables (quote/SignaturePopup convention); the
// data-borne catalog labels come bilingual from the server DTO.

export const L = {
  he: {
    dir: 'rtl',
    title: 'טופס הזמנות לסוכני נסיעות',
    greeting: (name, org) => `שלום ${name} · ${org}`,
    intro:
      'מלאו קבוצה אחת או יותר ושלחו הכל בבת אחת. כל קבוצה תטופל כהזמנה נפרדת.',
    requestNote:
      'שליחת הטופס היא בקשת הזמנה — ההזמנה תיכנס לתוקף רק לאחר אישור שלנו.',
    summary: {
      groups: (n) => (n === 1 ? 'קבוצה אחת' : `${n} קבוצות`),
      participants: (n) => `${n} משתתפים`,
      total: (n) => `סה״כ ${n} משתתפים`,
    },
    group: {
      title: (i) => `קבוצה ${i}`,
      complete: 'מלא ✓',
      incomplete: 'חסרים פרטים',
      groupName: 'שם הקבוצה',
      groupNamePh: 'לדוגמה: קבוצת בוקר — חברת אלפא',
      city: 'עיר',
      cityPh: '— בחרו עיר —',
      tour: 'סיור',
      tourPh: '— בחרו סיור —',
      date: 'תאריך',
      time: 'שעה',
      participants: 'מספר משתתפים',
      tourLanguage: 'שפת הסיור',
      tourLanguagePh: '— ללא העדפה —',
      onSiteTitle: 'נציג בשטח (אופציונלי)',
      onSiteHint: 'איש הקשר שמלווה את הקבוצה ביום הסיור.',
      onSiteName: 'שם הנציג',
      onSitePhone: 'טלפון הנציג',
      notes: 'הערות',
      duplicate: 'שכפול',
      remove: 'מחיקה',
      confirmRemove: 'למחוק את הקבוצה?',
    },
    addGroup: '+ הוספת קבוצה',
    footer: {
      confirmationsTitle: 'אישורים',
      confirm_reservation_request:
        'ידוע לי שזוהי בקשת הזמנה בלבד, וההזמנה תאושר סופית על ידי גרפיטיול.',
      confirm_details_correct: 'הפרטים שמסרתי נכונים ומלאים.',
      signatureTitle: 'חתימה (אחת עבור כל ההזמנה)',
      signTyped: 'הקלדת שם',
      signDrawn: 'ציור חתימה',
      signerNamePh: 'שם מלא',
      clear: 'ניקוי',
      submit: 'שליחת ההזמנה',
      submitting: 'שולח…',
    },
    problems: {
      required: 'שדה חובה',
      invalid: 'ערך לא תקין',
      past: 'התאריך כבר עבר',
      pair_required: 'יש למלא שם וגם טלפון',
      too_many: 'יותר מדי קבוצות',
      form: 'יש להשלים את הפרטים המסומנים',
      signature: 'חסרה חתימה',
      confirmations: 'יש לאשר את כל הסעיפים',
      network: 'שגיאה בשליחה — נסו שוב',
    },
    thanks: {
      title: 'ההזמנה התקבלה!',
      subtitle: (no) => `מספר בקשה ${no}`,
      note:
        'זוהי בקשת הזמנה. נעבור עליה ונחזור אליכם עם אישור סופי לכל קבוצה.',
      received: 'התקבל',
      processing: 'בטיפול',
      orderNo: (n) => `GOS-${n}`,
      downloadPdf: 'הורד הזמנה (PDF)',
      newReservation: 'הזמנה חדשה',
    },
    blocked: {
      notFound: 'הקישור אינו קיים.',
      inactive:
        'הקישור אינו פעיל כרגע. פנו אלינו לקבלת קישור מעודכן.',
    },
    loading: 'טוען…',
  },
  en: {
    dir: 'ltr',
    title: 'Travel Agent Reservation Form',
    greeting: (name, org) => `Hello ${name} · ${org}`,
    intro:
      'Fill in one or more groups and submit them together. Each group is handled as a separate booking.',
    requestNote:
      'Submitting this form is a reservation request — it becomes final only after our confirmation.',
    summary: {
      groups: (n) => (n === 1 ? '1 group' : `${n} groups`),
      participants: (n) => `${n} participants`,
      total: (n) => `Total: ${n} participants`,
    },
    group: {
      title: (i) => `Group ${i}`,
      complete: 'Complete ✓',
      incomplete: 'Missing details',
      groupName: 'Group name',
      groupNamePh: 'e.g. Morning group — Alpha Corp',
      city: 'City',
      cityPh: '— Select city —',
      tour: 'Tour',
      tourPh: '— Select tour —',
      date: 'Date',
      time: 'Time',
      participants: 'Participants',
      tourLanguage: 'Tour language',
      tourLanguagePh: '— No preference —',
      onSiteTitle: 'On-site contact (optional)',
      onSiteHint: 'The person accompanying the group on tour day.',
      onSiteName: 'Contact name',
      onSitePhone: 'Contact phone',
      notes: 'Notes',
      duplicate: 'Duplicate',
      remove: 'Delete',
      confirmRemove: 'Delete this group?',
    },
    addGroup: '+ Add group',
    footer: {
      confirmationsTitle: 'Confirmations',
      confirm_reservation_request:
        'I understand this is a reservation request only, subject to final confirmation by Grafitiyul.',
      confirm_details_correct: 'The details I provided are correct and complete.',
      signatureTitle: 'Signature (one for the entire reservation)',
      signTyped: 'Type name',
      signDrawn: 'Draw signature',
      signerNamePh: 'Full name',
      clear: 'Clear',
      submit: 'Submit reservation',
      submitting: 'Submitting…',
    },
    problems: {
      required: 'Required',
      invalid: 'Invalid value',
      past: 'Date already passed',
      pair_required: 'Both name and phone are needed',
      too_many: 'Too many groups',
      form: 'Please complete the highlighted fields',
      signature: 'Signature is missing',
      confirmations: 'Please accept all confirmations',
      network: 'Something went wrong — please try again',
    },
    thanks: {
      title: 'Reservation received!',
      subtitle: (no) => `Request number ${no}`,
      note:
        'This is a reservation request. We will review it and get back to you with a final confirmation for each group.',
      received: 'Received',
      processing: 'Processing',
      orderNo: (n) => `GOS-${n}`,
      downloadPdf: 'Download reservation (PDF)',
      newReservation: 'New reservation',
    },
    blocked: {
      notFound: 'This link does not exist.',
      inactive: 'This link is not active right now. Please contact us for an updated link.',
    },
    loading: 'Loading…',
  },
};

export const TOUR_LANGUAGES = [
  { value: 'he', he: 'עברית', en: 'Hebrew' },
  { value: 'en', he: 'אנגלית', en: 'English' },
  { value: 'es', he: 'ספרדית', en: 'Spanish' },
  { value: 'fr', he: 'צרפתית', en: 'French' },
  { value: 'ru', he: 'רוסית', en: 'Russian' },
];
