// Travel-agent reservation form — bilingual UI strings (he RTL / en LTR).
// House pattern: per-surface L tables (quote/SignaturePopup convention); the
// data-borne catalog labels come bilingual from the server DTO (commercial
// channel names — never internal product/variant/location names).

// Canonical tour-language options for the form. KEYS are the system-wide stable
// identifiers (Deal/ReservationGroup.tourLanguage; server-validated in
// intake.js) — never a translated label. English is the default (owner rule).
// Display labels are bilingual so the option reads naturally in the form's own
// language; the pricing surcharge is decided by the KEY, in data, on the server.
export const TOUR_LANGUAGE_OPTIONS = [
  { key: 'en', he: 'אנגלית', en: 'English' },
  { key: 'he', he: 'עברית', en: 'Hebrew' },
  { key: 'es', he: 'ספרדית', en: 'Spanish' },
  { key: 'fr', he: 'צרפתית', en: 'French' },
  { key: 'ru', he: 'רוסית', en: 'Russian' },
];
export const DEFAULT_TOUR_LANGUAGE = 'en';

export const L = {
  he: {
    dir: 'rtl',
    brandTag: 'TOURS & WORKSHOPS',
    title: 'טופס הזמנת פעילות לסוכני תיירות',
    intro: 'מלאו את פרטי הקבוצות. ניתן להוסיף כמה קבוצות לאותה בקשה. נעדכן אתכם כשההזמנה תאושר.',
    groupsTitle: 'הקבוצות שלכם',
    agentCard: {
      title: 'פרטי המזמין',
      name: 'שם',
      phone: 'טלפון',
      email: 'אימייל',
      company: 'חברת נסיעות',
    },
    group: {
      title: (i) => `קבוצה ${i}`,
      activityBadge: 'פעילות',
      city: 'עיר',
      cityPh: '— בחרו עיר —',
      activity: 'פעילות',
      activityPh: '— בחרו פעילות —',
      date: 'תאריך',
      time: 'שעה',
      participants: 'מספר משתתפים',
      guides: 'מספר מדריכים',
      tourLanguage: 'שפת הסיור',
      onSiteTitle: 'איש קשר בשטח (אופציונלי)',
      onSiteName: 'שם מלא',
      onSitePhone: 'טלפון נייד',
      notes: 'הערות / דגשים',
      collapse: 'כיווץ',
      expand: 'הרחבה',
      remove: 'מחיקה',
      confirmRemove: 'למחוק את הקבוצה?',
      incomplete: 'חסרים פרטים',
      collapsedNoActivity: 'קבוצה חדשה',
      collapsedLine: (parts) => parts.join(' · '),
    },
    addGroup: 'הוסף קבוצה נוספת',
    cancellation: {
      lines: [
        'תנאי הביטול הגמישים במיוחד לסוכני תיירות ידועים לי:',
        'עד 24 שעות לפני הפעילות ללא דמי ביטול.',
        'בפחות מ־24 שעות - דמי ביטול של 100%.',
      ],
    },
    invoice: {
      title: 'לאן לשלוח את החשבונית?',
      toMe: 'אליי (מזמין ההזמנה)',
      toFinance: 'לאיש הכספים',
      toOtherFinance: 'לאיש כספים אחר',
      financeName: 'שם מלא',
      financeEmail: 'אימייל',
      financePhone: 'טלפון',
      replaceAction: 'החלף לאיש כספים חדש',
      replacingNote: 'הגדרת איש כספים חדש במקום הקיים.',
      keepSaved: 'חזרה לאיש הכספים השמור',
    },
    footer: {
      signatureTitle: 'חתימה (אחת עבור כל הבקשה)',
      signTyped: 'הקלדת שם',
      signDrawn: 'ציור חתימה',
      signerNamePh: 'שם מלא',
      signerNameOptionalPh: 'שם מלא (לא חובה)',
      clear: 'ניקוי',
      submit: 'שליחת ההזמנה',
      submitting: 'שולח…',
    },
    problems: {
      required: 'שדה חובה',
      invalid: 'ערך לא תקין',
      past: 'התאריך כבר עבר',
      pair_required: 'יש למלא שם וגם טלפון',
      too_many: 'יותר מדי קבוצות',
      form: 'יש להשלים את הפרטים המסומנים',
      signature: 'חסרה חתימה',
      confirmations: 'יש לאשר את כל הסעיפים לפני השליחה',
      recipients: 'יש לבחור לפחות נמען אחד לחשבונית',
      financeDetails: 'יש להזין שם, אימייל וטלפון תקינים לאיש הכספים',
      network: 'שגיאה בשליחה — נסו שוב',
    },
    thanks: {
      title: 'ההזמנה התקבלה!',
      subtitle: (no) => `מספר בקשה ${no}`,
      note: 'זוהי בקשת הזמנה. נעבור עליה ונחזור אליכם עם אישור סופי לכל קבוצה.',
      received: 'התקבל',
      participants: (n) => `${n} משתתפים`,
      orderNo: (n) => `GOS-${n}`,
      downloadPdf: 'הורדת סיכום ההזמנה',
      preparingPdf: 'מכין את סיכום ההזמנה…',
      newReservation: 'הזמנה חדשה',
    },
    blocked: {
      notFound: 'הקישור אינו קיים.',
      inactive: 'הקישור אינו פעיל כרגע. פנו אלינו לקבלת קישור מעודכן.',
    },
  },
  en: {
    dir: 'ltr',
    brandTag: 'TOURS & WORKSHOPS',
    title: 'Activity Reservation Form for Travel Agents',
    intro: "Fill in the group details. You can add several groups to one request. We'll update you once the reservation is approved.",
    groupsTitle: 'Your groups',
    agentCard: {
      title: 'Booker details',
      name: 'Name',
      phone: 'Phone',
      email: 'Email',
      company: 'Travel company',
    },
    group: {
      title: (i) => `Group ${i}`,
      activityBadge: 'Activity',
      city: 'City',
      cityPh: '— Select city —',
      activity: 'Activity',
      activityPh: '— Select activity —',
      date: 'Date',
      time: 'Time',
      participants: 'Participants',
      guides: 'Number of guides',
      tourLanguage: 'Tour language',
      onSiteTitle: 'On-site contact (optional)',
      onSiteName: 'Full name',
      onSitePhone: 'Mobile phone',
      notes: 'Notes / Highlights',
      collapse: 'Collapse',
      expand: 'Expand',
      remove: 'Delete',
      confirmRemove: 'Delete this group?',
      incomplete: 'Missing details',
      collapsedNoActivity: 'New group',
      collapsedLine: (parts) => parts.join(' · '),
    },
    addGroup: 'Add another group',
    cancellation: {
      lines: [
        'I acknowledge the especially flexible cancellation terms for travel agents:',
        'Up to 24 hours before the activity — no cancellation fee.',
        'Less than 24 hours — a 100% cancellation fee.',
      ],
    },
    invoice: {
      title: 'Where should we send the invoice?',
      toMe: 'To me (the booker)',
      toFinance: 'To the finance contact',
      toOtherFinance: 'To another finance contact',
      financeName: 'Full name',
      financeEmail: 'Email',
      financePhone: 'Phone',
      replaceAction: 'Replace with a new finance contact',
      replacingNote: 'Defining a new finance contact to replace the saved one.',
      keepSaved: 'Keep the saved finance contact',
    },
    footer: {
      signatureTitle: 'Signature (one for the entire request)',
      signTyped: 'Type name',
      signDrawn: 'Draw signature',
      signerNamePh: 'Full name',
      signerNameOptionalPh: 'Full name (optional)',
      clear: 'Clear',
      submit: 'Submit reservation',
      submitting: 'Submitting…',
    },
    problems: {
      required: 'Required',
      invalid: 'Invalid value',
      past: 'Date already passed',
      pair_required: 'Both name and phone are needed',
      too_many: 'Too many groups',
      form: 'Please complete the highlighted fields',
      signature: 'Signature is missing',
      confirmations: 'Please accept all confirmations before submitting',
      recipients: 'Please choose at least one invoice recipient',
      financeDetails: 'Please enter a valid finance contact name, email and phone',
      network: 'Something went wrong — please try again',
    },
    thanks: {
      title: 'Reservation received!',
      subtitle: (no) => `Request number ${no}`,
      note: 'This is a reservation request. We will review it and get back to you with a final confirmation for each group.',
      received: 'Received',
      participants: (n) => `${n} participants`,
      orderNo: (n) => `GOS-${n}`,
      downloadPdf: 'Download reservation summary',
      preparingPdf: 'Preparing your reservation summary…',
      newReservation: 'New reservation',
    },
    blocked: {
      notFound: 'This link does not exist.',
      inactive: 'This link is not active right now. Please contact us for an updated link.',
    },
  },
};
