// Travel-agent reservation form — bilingual UI strings (he RTL / en LTR).
// House pattern: per-surface L tables (quote/SignaturePopup convention); the
// data-borne catalog labels come bilingual from the server DTO (commercial
// channel names — never internal product/variant/location names).

export const L = {
  he: {
    dir: 'rtl',
    brandTag: 'TOURS & WORKSHOPS',
    title: 'טופס הזמנת פעילות לסוכני תיירות',
    intro: 'מלאו את פרטי הקבוצות. ניתן להוסיף כמה קבוצות לאותה בקשה, ונציג יחזור אליכם בהקדם.',
    groupsTitle: 'הקבוצות שלכם',
    summary: {
      title: 'סיכום הבקשה',
      groups: 'מספר קבוצות',
      participants: 'סה"כ משתתפים',
      activities: 'פעילויות',
      approvalNote: 'ההזמנה כפופה לאישור גרפיטיול. נציג יחזור אליכם בהקדם.',
    },
    agentCard: {
      title: 'איש קשר להזמנה',
      name: 'שם',
      phone: 'טלפון',
      email: 'אימייל',
      company: 'חברת נסיעות',
    },
    group: {
      title: (i) => `קבוצה ${i}`,
      activityBadge: 'פעילות',
      city: 'עיר',
      cityPh: '— בחרו עיר —',
      activity: 'פעילות',
      activityPh: '— בחרו פעילות —',
      date: 'תאריך',
      time: 'שעה',
      participants: 'מספר משתתפים',
      onSiteTitle: 'איש קשר בשטח (אופציונלי)',
      onSiteName: 'שם מלא',
      onSitePhone: 'טלפון נייד',
      notes: 'הערות',
      collapse: 'כיווץ',
      expand: 'הרחבה',
      remove: 'מחיקה',
      confirmRemove: 'למחוק את הקבוצה?',
      incomplete: 'חסרים פרטים',
      collapsedNoActivity: 'קבוצה חדשה',
      collapsedLine: (parts) => parts.join(' · '),
    },
    addGroup: 'הוסף קבוצה נוספת',
    footer: {
      confirm_reservation_request: 'ידוע לי שההזמנה כפופה לאישור גרפיטיול.',
      signatureTitle: 'חתימה (אחת עבור כל הבקשה)',
      signTyped: 'הקלדת שם',
      signDrawn: 'ציור חתימה',
      signerNamePh: 'שם מלא',
      clear: 'ניקוי',
      submit: 'שליחת ההזמנה',
      submitting: 'שולח…',
    },
    problems: {
      required: 'שדה חובה',
      invalid: 'ערך לא תקין',
      past: 'התאריך כבר עבר',
      pair_required: 'יש למלא שם וגם טלפון',
      too_many: 'יותר מדי קבוצות',
      form: 'יש להשלים את הפרטים המסומנים',
      signature: 'חסרה חתימה',
      confirmations: 'יש לאשר את הסעיף לפני השליחה',
      network: 'שגיאה בשליחה — נסו שוב',
    },
    thanks: {
      title: 'ההזמנה התקבלה!',
      subtitle: (no) => `מספר בקשה ${no}`,
      note: 'זוהי בקשת הזמנה. נעבור עליה ונחזור אליכם עם אישור סופי לכל קבוצה.',
      received: 'התקבל',
      participants: (n) => `${n} משתתפים`,
      orderNo: (n) => `GOS-${n}`,
      downloadPdf: 'הורד הזמנה (PDF)',
      newReservation: 'הזמנה חדשה',
    },
    blocked: {
      notFound: 'הקישור אינו קיים.',
      inactive: 'הקישור אינו פעיל כרגע. פנו אלינו לקבלת קישור מעודכן.',
    },
  },
  en: {
    dir: 'ltr',
    brandTag: 'TOURS & WORKSHOPS',
    title: 'Activity Reservation Form for Travel Agents',
    intro: 'Fill in the group details. You can add several groups to one request, and we will get back to you shortly.',
    groupsTitle: 'Your groups',
    summary: {
      title: 'Request summary',
      groups: 'Groups',
      participants: 'Total participants',
      activities: 'Activities',
      approvalNote: 'The reservation is subject to Grafitiyul approval. We will get back to you shortly.',
    },
    agentCard: {
      title: 'Booking contact',
      name: 'Name',
      phone: 'Phone',
      email: 'Email',
      company: 'Travel company',
    },
    group: {
      title: (i) => `Group ${i}`,
      activityBadge: 'Activity',
      city: 'City',
      cityPh: '— Select city —',
      activity: 'Activity',
      activityPh: '— Select activity —',
      date: 'Date',
      time: 'Time',
      participants: 'Participants',
      onSiteTitle: 'On-site contact (optional)',
      onSiteName: 'Full name',
      onSitePhone: 'Mobile phone',
      notes: 'Notes',
      collapse: 'Collapse',
      expand: 'Expand',
      remove: 'Delete',
      confirmRemove: 'Delete this group?',
      incomplete: 'Missing details',
      collapsedNoActivity: 'New group',
      collapsedLine: (parts) => parts.join(' · '),
    },
    addGroup: 'Add another group',
    footer: {
      confirm_reservation_request: 'I understand the reservation is subject to Grafitiyul approval.',
      signatureTitle: 'Signature (one for the entire request)',
      signTyped: 'Type name',
      signDrawn: 'Draw signature',
      signerNamePh: 'Full name',
      clear: 'Clear',
      submit: 'Submit reservation',
      submitting: 'Submitting…',
    },
    problems: {
      required: 'Required',
      invalid: 'Invalid value',
      past: 'Date already passed',
      pair_required: 'Both name and phone are needed',
      too_many: 'Too many groups',
      form: 'Please complete the highlighted fields',
      signature: 'Signature is missing',
      confirmations: 'Please confirm before submitting',
      network: 'Something went wrong — please try again',
    },
    thanks: {
      title: 'Reservation received!',
      subtitle: (no) => `Request number ${no}`,
      note: 'This is a reservation request. We will review it and get back to you with a final confirmation for each group.',
      received: 'Received',
      participants: (n) => `${n} participants`,
      orderNo: (n) => `GOS-${n}`,
      downloadPdf: 'Download reservation (PDF)',
      newReservation: 'New reservation',
    },
    blocked: {
      notFound: 'This link does not exist.',
      inactive: 'This link is not active right now. Please contact us for an updated link.',
    },
  },
};
